[fr]
  languageName = "Français"
  contentDir = "content/fr"
  weight = 10
  [fr.params]
    languageISO = "FR"
    languageTag = "fr"
    #footer = 'Brought to you by <a class="text-muted" href="https://thulite.io/">Thulite</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

